server:
  port: 18051
eureka:
  instance:
    hostname: 127.0.0.1
#    hostname: 183.207.183.130
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enableSelfPreservation: false
